"""V2 alignment fixtures: golden values for the V2-min default configuration.

Verified configuration (config_tag = "v2_min_default")
--------------------------------------------------------
  chat_template : MinimalChatTemplate   (<|role|> markers, no model-specific tokens)
  tokenizer     : CharTokenizer         (ord(c) per character, NOT a real LLM tokenizer)
  block_builder : SimpleBlockBuilder    (SHA-256, comma-joined payload, NOT SipHash)
  block_size    : 16 (default) or as noted per fixture

ALIGNMENT STATUS: ``internal_only``
  These golden values verify that the V2-min pipeline is SELF-CONSISTENT
  across runs.  They do NOT certify alignment with any external framework
  (Qwen, LLaMA, vLLM, HuggingFace, etc.).

  A later alignment pass will require:
  1. Replace CharTokenizer with a real tokenizer (e.g. HFTokenizerAdapter).
  2. Replace MinimalChatTemplate with the model's actual Jinja template.
  3. Replace _sha256_block_default with the framework's block hash (SipHash).
  4. Re-run compute_goldens() and store new golden values.

Validation target matrix
--------------------------
  Layer 1: messages → rendered_prompt
    Verified by: expected_rendered_prompt (human-readable, easy to review)

  Layer 2: rendered_prompt → token_ids
    Verified by: expected_token_ids (computed by CharTokenizer.encode)

  Layer 3a: token_ids → block_ids (hash of each full block)
    Verified by: expected_block_ids (computed by SimpleBlockBuilder + _sha256_block_default)

  Layer 3b: token_ids → leftover_token_count (tokens after last full block)
    Verified by: expected_leftover_token_count

Each layer can fail independently, making it possible to pinpoint exactly
which component drifted when a test fails.
"""
from __future__ import annotations

from dataclasses import dataclass, field

from block_prefix_analyzer.v2.schema import Message


@dataclass
class V2AlignmentFixture:
    """One alignment test case with expected outputs for each pipeline layer.

    Attributes
    ----------
    name:
        Short identifier used in test names and diagnostic output.
    description:
        Human-readable description of what this fixture is testing.
    config_tag:
        Which adapter configuration produced these golden values.
        ``"v2_min_default"`` means MinimalChatTemplate + CharTokenizer +
        SimpleBlockBuilder(block_size).
    alignment_status:
        ``"internal_only"`` — verified against our own adapters only.
        ``"pending_framework"`` — slot reserved for future framework-aligned values.
    messages:
        Input messages for the chat template.
    block_size:
        Block size used when computing block golden values.
    expected_rendered_prompt:
        Expected output of ChatTemplateAdapter.render(messages).
        Always set; human-readable and reviewable without running code.
    expected_token_ids:
        Expected output of TokenizerAdapter.encode(rendered_prompt).
        ``None`` means "pending framework-aligned verification".
    expected_block_ids:
        Expected output of BlockBuilder.build(token_ids).block_ids.
        ``None`` means "pending framework-aligned verification".
    expected_leftover_token_count:
        Expected BlockBuildResult.leftover_token_count.
        ``None`` means "pending framework-aligned verification".
    framework_notes:
        Free-form notes about what would need to change for framework alignment.
    """

    name: str
    description: str
    config_tag: str
    alignment_status: str
    messages: list[Message]
    block_size: int
    expected_rendered_prompt: str
    expected_token_ids: list[int] | None
    expected_block_ids: list[int] | None
    expected_leftover_token_count: int | None
    framework_notes: str = ""


# ---------------------------------------------------------------------------
# Fixtures for config_tag = "v2_min_default"
# (MinimalChatTemplate + CharTokenizer + SimpleBlockBuilder)
#
# Golden values were generated by running:
#   src/block_prefix_analyzer/v2/adapters/ with default adapters
# and are exact for Python 3.10+ (ord() and hashlib.sha256 are stable).
# ---------------------------------------------------------------------------

FIXTURE_SINGLE_USER = V2AlignmentFixture(
    name="single_user",
    description="Single user turn — baseline, minimal template markers",
    config_tag="v2_min_default",
    alignment_status="internal_only",
    messages=[Message(role="user", content="Hello")],
    block_size=16,
    expected_rendered_prompt="<|user|>\nHello\n<|assistant|>",
    expected_token_ids=[
        60, 124, 117, 115, 101, 114, 124, 62,  # <|user|>
        10,                                      # \n
        72, 101, 108, 108, 111,                  # Hello
        10,                                      # \n
        60, 124, 97, 115, 115, 105, 115, 116, 97, 110, 116, 124, 62,  # <|assistant|>
    ],
    expected_block_ids=[2019794131847563612],
    expected_leftover_token_count=12,
    framework_notes=(
        "MinimalChatTemplate does not add BOS/EOS or role-specific special tokens. "
        "A real Qwen template would produce different tokens here."
    ),
)

FIXTURE_SYSTEM_USER = V2AlignmentFixture(
    name="system_user",
    description="System prompt + user turn — verifies system role formatting",
    config_tag="v2_min_default",
    alignment_status="internal_only",
    messages=[
        Message(role="system", content="You are helpful."),
        Message(role="user", content="Hello"),
    ],
    block_size=16,
    expected_rendered_prompt=(
        "<|system|>\nYou are helpful.\n"
        "<|user|>\nHello\n"
        "<|assistant|>"
    ),
    expected_token_ids=[
        60, 124, 115, 121, 115, 116, 101, 109, 124, 62,   # <|system|>
        10,                                                 # \n
        89, 111, 117, 32, 97, 114, 101, 32, 104, 101, 108, 112, 102, 117, 108, 46,  # You are helpful.
        10,                                                 # \n
        60, 124, 117, 115, 101, 114, 124, 62,              # <|user|>
        10,                                                 # \n
        72, 101, 108, 108, 111,                            # Hello
        10,                                                 # \n
        60, 124, 97, 115, 115, 105, 115, 116, 97, 110, 116, 124, 62,  # <|assistant|>
    ],
    expected_block_ids=[
        3585893510292524636,
        10883147154380768204,
        8052646049224464661,
    ],
    expected_leftover_token_count=8,
    framework_notes="System role token varies across models; Qwen uses <|im_start|>system.",
)

FIXTURE_MULTI_TURN = V2AlignmentFixture(
    name="multi_turn",
    description="4-message dialogue — verifies assistant and multi-user turns",
    config_tag="v2_min_default",
    alignment_status="internal_only",
    messages=[
        Message(role="system", content="Be concise."),
        Message(role="user", content="What is 2+2?"),
        Message(role="assistant", content="4"),
        Message(role="user", content="Why?"),
    ],
    block_size=16,
    expected_rendered_prompt=(
        "<|system|>\nBe concise.\n"
        "<|user|>\nWhat is 2+2?\n"
        "<|assistant|>\n4\n"
        "<|user|>\nWhy?\n"
        "<|assistant|>"
    ),
    expected_token_ids=[
        60, 124, 115, 121, 115, 116, 101, 109, 124, 62, 10,   # <|system|>\n
        66, 101, 32, 99, 111, 110, 99, 105, 115, 101, 46, 10, # Be concise.\n
        60, 124, 117, 115, 101, 114, 124, 62, 10,             # <|user|>\n
        87, 104, 97, 116, 32, 105, 115, 32, 50, 43, 50, 63, 10,  # What is 2+2?\n
        60, 124, 97, 115, 115, 105, 115, 116, 97, 110, 116, 124, 62, 10,  # <|assistant|>\n
        52, 10,                                               # 4\n
        60, 124, 117, 115, 101, 114, 124, 62, 10,             # <|user|>\n
        87, 104, 121, 63, 10,                                 # Why?\n
        60, 124, 97, 115, 115, 105, 115, 116, 97, 110, 116, 124, 62,  # <|assistant|>
    ],
    expected_block_ids=[
        9515653973801000835,
        8284071217346629265,
        9318804748086747729,
        14618692307645007565,
        1487574213669598798,
    ],
    expected_leftover_token_count=8,
    framework_notes="Multi-turn formatting varies significantly across models.",
)

FIXTURE_EMPTY_SYSTEM_CONTENT = V2AlignmentFixture(
    name="empty_system_content",
    description="System message with empty content — tests edge case handling",
    config_tag="v2_min_default",
    alignment_status="internal_only",
    messages=[
        Message(role="system", content=""),
        Message(role="user", content="Hi"),
    ],
    block_size=16,
    # MinimalChatTemplate uses <|role|> (no \ncontent) when content is empty
    expected_rendered_prompt="<|system|>\n<|user|>\nHi\n<|assistant|>",
    expected_token_ids=[
        60, 124, 115, 121, 115, 116, 101, 109, 124, 62, 10,  # <|system|>\n
        60, 124, 117, 115, 101, 114, 124, 62, 10,             # <|user|>\n
        72, 105, 10,                                          # Hi\n
        60, 124, 97, 115, 115, 105, 115, 116, 97, 110, 116, 124, 62,  # <|assistant|>
    ],
    expected_block_ids=[12149516200070827893, 7408051923669612928],
    expected_leftover_token_count=4,
    framework_notes=(
        "Empty system content: MinimalChatTemplate omits the newline+content "
        "segment but still emits the role marker. Real frameworks may omit the "
        "system block entirely or insert a placeholder."
    ),
)

FIXTURE_UNICODE_CONTENT = V2AlignmentFixture(
    name="unicode_content",
    description="Non-ASCII content (CJK) — verifies CharTokenizer unicode handling",
    config_tag="v2_min_default",
    alignment_status="internal_only",
    messages=[Message(role="user", content="你好")],
    block_size=16,
    expected_rendered_prompt="<|user|>\n你好\n<|assistant|>",
    # ord("你")=20320, ord("好")=22909; all other chars are ASCII
    expected_token_ids=[
        60, 124, 117, 115, 101, 114, 124, 62, 10,  # <|user|>\n
        20320, 22909,                               # 你好
        10,                                         # \n
        60, 124, 97, 115, 115, 105, 115, 116, 97, 110, 116, 124, 62,  # <|assistant|>
    ],
    expected_block_ids=[11587244095281347356],
    expected_leftover_token_count=9,
    framework_notes=(
        "CharTokenizer maps each char to ord(c); CJK characters produce token IDs "
        "in range [0x4E00, 0x9FFF]. A real BPE tokenizer would merge these "
        "characters differently — typically 1–3 bytes per CJK char."
    ),
)

FIXTURE_BLOCK_BOUNDARY_BS4 = V2AlignmentFixture(
    name="exact_block_boundary_bs4",
    description="Small block_size=4 — verifies multiple block hashes and boundary math",
    config_tag="v2_min_default",
    alignment_status="internal_only",
    messages=[Message(role="user", content="AB")],
    block_size=4,
    expected_rendered_prompt="<|user|>\nAB\n<|assistant|>",
    expected_token_ids=[
        60, 124, 117, 115, 101, 114, 124, 62, 10,  # <|user|>\n
        65, 66,                                     # AB
        10,                                         # \n
        60, 124, 97, 115, 115, 105, 115, 116, 97, 110, 116, 124, 62,  # <|assistant|>
    ],
    expected_block_ids=[
        13047528521002944359,  # [60, 124, 117, 115]
        10296125557070268830,  # [101, 114, 124, 62]
        8461974210891803967,   # [10, 65, 66, 10]
        12898532311768444974,  # [60, 124, 97, 115]
        3611601405256801149,   # [115, 105, 115, 116]
        615214793314011238,    # [97, 110, 116, 124]
    ],
    expected_leftover_token_count=1,  # [62] is leftover
    framework_notes=(
        "This fixture uses block_size=4 (not the default 16) to test exact "
        "block boundary logic with many blocks.  Real KV-cache block sizes "
        "are typically 16–32 tokens."
    ),
)

# ---------------------------------------------------------------------------
# Placeholder fixture — reserved for future framework-aligned golden values
# ---------------------------------------------------------------------------

FIXTURE_PENDING_FRAMEWORK = V2AlignmentFixture(
    name="pending_qwen_alignment",
    description=(
        "PLACEHOLDER: reserved for Qwen-aligned golden values. "
        "Fill in expected_* fields after running real Qwen tokenizer + template."
    ),
    config_tag="qwen_vllm_aligned",
    alignment_status="pending_framework",
    messages=[
        Message(role="system", content="You are a helpful assistant."),
        Message(role="user", content="Hello"),
    ],
    block_size=16,
    expected_rendered_prompt=(
        # To be filled: output of Qwen's apply_chat_template()
        # e.g. "<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n..."
        "PENDING"
    ),
    expected_token_ids=None,   # pending: run AutoTokenizer("Qwen/Qwen2-7B").encode(prompt)
    expected_block_ids=None,   # pending: run with SipHash or vLLM block hash
    expected_leftover_token_count=None,
    framework_notes=(
        "Replace expected_rendered_prompt, expected_token_ids, expected_block_ids "
        "with actual output from Qwen vLLM pipeline.  Then change alignment_status "
        "to 'framework_verified'."
    ),
)

# ---------------------------------------------------------------------------
# Exported fixture registry
# ---------------------------------------------------------------------------

#: All fixtures that have fully-specified golden values (no None fields).
VERIFIED_FIXTURES: list[V2AlignmentFixture] = [
    FIXTURE_SINGLE_USER,
    FIXTURE_SYSTEM_USER,
    FIXTURE_MULTI_TURN,
    FIXTURE_EMPTY_SYSTEM_CONTENT,
    FIXTURE_UNICODE_CONTENT,
    FIXTURE_BLOCK_BOUNDARY_BS4,
]

#: All fixtures including pending placeholders.
ALL_FIXTURES: list[V2AlignmentFixture] = VERIFIED_FIXTURES + [FIXTURE_PENDING_FRAMEWORK]
